### ISSUE TITLE
ToneGenerator frequency range

### ISSUE THREAD

**Issue by endolith** [FigBug/slPlugins#1]
Is there a technical reason why ToneGenerator is limited to 10 kHz, or was it just not thought to be useful?  (It would be useful to me)

https://github.com/FigBug/slPlugins/blob/master/plugins/ToneGenerator/Source/PluginProcessor.cpp#L136

**Comment by FigBug** [comment]
Above 10k, all the waveforms other than sine will pretty much just turn into sine. So I didn't think there was much point. I don't really want to change it now and break peoples presets.

**Comment by FigBug** [comment]
Actually, presets won't break. Just automation and I doubt that many people automate the frequency anyway. Updated.
