### ISSUE TITLE
VST3 ToneGenerator is broken with JUCE7

### ISSUE THREAD

**Issue by KottV** [FigBug/slPlugins#4]
Hi,

I've tested with ToneGenerator only (Lin and Win).
Build prior JUCE7 tag:
![изображение](https://user-images.githubusercontent.com/4686351/175185360-75acea7c-e960-4382-83e8-cd77a4a7f177.png)

After (set sine value+, then adjust/reduce freq):
![изображение](https://user-images.githubusercontent.com/4686351/175185526-64bc16e4-4f7a-4f8e-96f6-190abba28979.png)

**Comment by KottV** [comment]
I's due this change https://github.com/juce-framework/JUCE/commit/964a1aa870a05b48cee46faa3375946c8ff7f4cd (compiled with JUCE prior to this commit works fine)

the code is need to be updated for the new API

**Comment by FigBug** [comment]
Fixed in a6273f2c9f25f6945cc21df1b3e4d2ff02d7894c
