### ISSUE TITLE
LV2 knobs aren't working

### ISSUE THREAD

**Issue by KottV** [FigBug/slPlugins#7]
Hi,

Knobs don't react in LV2 builds. VST3 works:
![изображение](https://user-images.githubusercontent.com/4686351/179642757-10b9862c-7215-4775-ac28-9f646c707094.png)

**Comment by KottV** [comment]
problem is in the busses setup, if I disable its configuration
```
target_compile_definitions(ToneGenerator
  PUBLIC
    JUCE_QUICKTIME=disabled
    JUCE_USE_CURL=0
    JUCE_WEB_BROWSER=0
    JUCE_MODAL_LOOPS_PERMITTED=1
    JUCE_JACK=1
    JUCE_REPORT_APP_USAGE=0
    JUCE_DISPLAY_SPLASH_SCREEN=0

#    JucePlugin_MaxNumInputChannels=0
#    JucePlugin_MaxNumOutputChannels=1
#    JucePlugin_PreferredChannelConfigurations=0,1
)
```
then plugin works
reported here https://forum.juce.com/t/lv2-issues/52412/2

**Comment by FigBug** [comment]
I've updated juce and rebuilt. Can you test again?

**Comment by KottV** [comment]
Tested, the same. The problem is in JUCE LV2 busses config.

**Comment by KottV** [comment]
It's fixed https://github.com/juce-framework/JUCE/commit/7ebd34012cb81f1cdece5c34da2eb8f83d829085

**Comment by FigBug** [comment]
Juce finally builds again, so everything is updated and I consider this fixed.
